In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import random

%matplotlib inline
pd.set_option('max_rows',20000)
pd.set_option('max_columns',11)

from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [2]:
test = pd.read_csv("test.csv")

In [3]:
test

PatientID  Pregnancies  PlasmaGlucose  DiastolicBloodPressure  \
0    1882185            9            104                      51   
1    1662484            6             73                      61   
2    1228510            4            115                      50   

   TricepsThickness  SerumInsulin        BMI  DiabetesPedigree  Age  
0                 7            24  27.369832          1.350472   43  
1                35            24  18.743674          0.158365   23  
2                29           243  34.692154          0.079019   23

In [4]:
test['AgeLog'] = np.log(test['Age'])

In [5]:
test

PatientID  Pregnancies  PlasmaGlucose  DiastolicBloodPressure  \
0    1882185            9            104                      51   
1    1662484            6             73                      61   
2    1228510            4            115                      50   

   TricepsThickness  SerumInsulin        BMI  DiabetesPedigree  Age    AgeLog  
0                 7            24  27.369832          1.350472   43  3.761200  
1                35            24  18.743674          0.158365   23  3.135494  
2                29           243  34.692154          0.079019   23  3.135494

In [6]:
test = test.drop(['Age'],axis=1)

In [7]:
test

PatientID  Pregnancies  PlasmaGlucose  DiastolicBloodPressure  \
0    1882185            9            104                      51   
1    1662484            6             73                      61   
2    1228510            4            115                      50   

   TricepsThickness  SerumInsulin        BMI  DiabetesPedigree    AgeLog  
0                 7            24  27.369832          1.350472  3.761200  
1                35            24  18.743674          0.158365  3.135494  
2                29           243  34.692154          0.079019  3.135494

In [8]:
X_scalar = test[['PlasmaGlucose','DiastolicBloodPressure','TricepsThickness','SerumInsulin','BMI']]

In [9]:
X_scalar.shape

(3, 5)

In [10]:
X_scalar.values

array([[104.        ,  51.        ,   7.        ,  24.        ,
         27.36983156],
       [ 73.        ,  61.        ,  35.        ,  24.        ,
         18.74367404],
       [115.        ,  50.        ,  29.        , 243.        ,
         34.69215364]])

In [11]:
X_minmax = test[['Pregnancies','DiabetesPedigree','AgeLog']]

In [12]:
X_minmax.shape

(3, 3)

In [13]:
X_minmax.values

array([[9.        , 1.35047205, 3.76120012],
       [6.        , 0.15836498, 3.13549422],
       [4.        , 0.07901857, 3.13549422]])

### Use StandardScaler method

In [14]:
scaler = StandardScaler()

In [15]:
X_scale_new = scaler.fit_transform(X_scalar)

In [16]:
X_scale_new

array([[ 0.3748975 , -0.60404045, -1.38462194, -0.70710678,  0.06667678],
       [-1.36837589,  1.40942772,  0.94154292, -0.70710678, -1.25672126],
       [ 0.99347838, -0.80538727,  0.44307902,  1.41421356,  1.19004448]])

In [17]:
X_scale_new = pd.DataFrame(X_scale_new, columns=X_scalar.columns)

In [18]:
X_scale_new.head()

PlasmaGlucose  DiastolicBloodPressure  TricepsThickness  SerumInsulin  \
0       0.374898               -0.604040         -1.384622     -0.707107   
1      -1.368376                1.409428          0.941543     -0.707107   
2       0.993478               -0.805387          0.443079      1.414214   

        BMI  
0  0.066677  
1 -1.256721  
2  1.190044

### Use MinMax method

In [19]:
minmax = MinMaxScaler()

In [20]:
X_mm_new = minmax.fit_transform(X_minmax)

In [21]:
X_mm_new

array([[1.        , 1.        , 1.        ],
       [0.4       , 0.06240607, 0.        ],
       [0.        , 0.        , 0.        ]])

In [22]:
X_mm_new = pd.DataFrame(X_mm_new, columns=X_minmax.columns)

In [23]:
X_mm_new.head()

Pregnancies  DiabetesPedigree  AgeLog
0          1.0          1.000000     1.0
1          0.4          0.062406     0.0
2          0.0          0.000000     0.0

### Merge the transformed dataset to existing one

In [24]:
test

PatientID  Pregnancies  PlasmaGlucose  DiastolicBloodPressure  \
0    1882185            9            104                      51   
1    1662484            6             73                      61   
2    1228510            4            115                      50   

   TricepsThickness  SerumInsulin        BMI  DiabetesPedigree    AgeLog  
0                 7            24  27.369832          1.350472  3.761200  
1                35            24  18.743674          0.158365  3.135494  
2                29           243  34.692154          0.079019  3.135494

In [25]:
test = test.drop(['Pregnancies','PlasmaGlucose','DiastolicBloodPressure','TricepsThickness',
               'SerumInsulin','BMI','DiabetesPedigree','AgeLog'],axis=1)

In [26]:
test

PatientID
0    1882185
1    1662484
2    1228510

In [27]:
testnew = pd.concat([test,X_scale_new,X_mm_new],axis=1)

In [28]:
testnew

PatientID  PlasmaGlucose  DiastolicBloodPressure  TricepsThickness  \
0    1882185       0.374898               -0.604040         -1.384622   
1    1662484      -1.368376                1.409428          0.941543   
2    1228510       0.993478               -0.805387          0.443079   

   SerumInsulin       BMI  Pregnancies  DiabetesPedigree  AgeLog  
0     -0.707107  0.066677          1.0          1.000000     1.0  
1     -0.707107 -1.256721          0.4          0.062406     0.0  
2      1.414214  1.190044          0.0          0.000000     0.0

In [29]:
testnew.describe()

PatientID  PlasmaGlucose  DiastolicBloodPressure  TricepsThickness  \
count  3.000000e+00   3.000000e+00            3.000000e+00      3.000000e+00   
mean   1.591060e+06   2.960595e-16           -3.700743e-17     -7.401487e-17   
std    3.326392e+05   1.224745e+00            1.224745e+00      1.224745e+00   
min    1.228510e+06  -1.368376e+00           -8.053873e-01     -1.384622e+00   
25%    1.445497e+06  -4.967392e-01           -7.047139e-01     -4.707715e-01   
50%    1.662484e+06   3.748975e-01           -6.040404e-01      4.430790e-01   
75%    1.772334e+06   6.841879e-01            4.026936e-01      6.923110e-01   
max    1.882185e+06   9.934784e-01            1.409428e+00      9.415429e-01   

       SerumInsulin           BMI  Pregnancies  DiabetesPedigree    AgeLog  
count      3.000000  3.000000e+00     3.000000          3.000000  3.000000  
mean       0.000000  2.960595e-16     0.466667          0.354135  0.333333  
std        1.224745  1.224745e+00     0.503322          0.560205  0.577350  
min       -0.707107 -1.256721e+00     0.000000          0.000000  0.000000  
25%       -0.707107 -5.950222e-01     0.200000          0.031203  0.000000  
50%       -0.707107  6.667678e-02     0.400000          0.062406  0.000000  
75%        0.353553  6.283606e-01     0.700000          0.531203  0.500000  
max        1.414214  1.190044e+00     1.000000          1.000000  1.000000

In [30]:
testnew = testnew.drop(['PatientID'],axis=1)

In [31]:
testnew

PlasmaGlucose  DiastolicBloodPressure  TricepsThickness  SerumInsulin  \
0       0.374898               -0.604040         -1.384622     -0.707107   
1      -1.368376                1.409428          0.941543     -0.707107   
2       0.993478               -0.805387          0.443079      1.414214   

        BMI  Pregnancies  DiabetesPedigree  AgeLog  
0  0.066677          1.0          1.000000     1.0  
1 -1.256721          0.4          0.062406     0.0  
2  1.190044          0.0          0.000000     0.0

In [32]:
#Rearrange columns
testnew = testnew[['Pregnancies','PlasmaGlucose','DiastolicBloodPressure','TricepsThickness',
          'SerumInsulin','BMI','DiabetesPedigree','AgeLog']]

In [33]:
testnew

Pregnancies  PlasmaGlucose  DiastolicBloodPressure  TricepsThickness  \
0          1.0       0.374898               -0.604040         -1.384622   
1          0.4      -1.368376                1.409428          0.941543   
2          0.0       0.993478               -0.805387          0.443079   

   SerumInsulin       BMI  DiabetesPedigree  AgeLog  
0     -0.707107  0.066677          1.000000     1.0  
1     -0.707107 -1.256721          0.062406     0.0  
2      1.414214  1.190044          0.000000     0.0

In [34]:
#Save to a new csv file
#testnew.to_csv("testcleaned.csv",index=False)